### ISSUE TITLE
data-loss by 'mass-adding' computers with veyon-ctl

### ISSUE THREAD

**Issue by chbmeyer** [veyon/veyon#446] opened 2018-10-24 21:21 UTC
Hello there,
I'm wondering why LDAP authentication isn't possible via kerberos.
Since I don't want to add a veyon-LDAP-user just for reading LDAP entries, I just process the list from AD with the command
net -Pe ads search '(objectClass=computer)' distinguishedName

I then looped through rooms and computers and added them (one after the other) to veyons configuration (under Debian):
while read hostname; do
   veyon-ctl networkobjects add computer $hostname ...
done
I noticed that only a few computers showed up in veyon and found out that obviously veyon-ctl exits before finishing it's work completely. So 'mass-adding' one-by-one every time starts a new veyon-ctl before writing the last entry. Adding a 'sleep .25' reduces data-loss.

In the meantime I found out that 'import'-ing a textfile works way better without 'sleep'-ing. So I'm no longer bitten by this, but I thought you should know about it.

Christian

**Comment by tobydox** [comment] 2018-11-07 14:41
Thank you very much for the bug report! I wonder why veyon-ctl exits before writing as even on Windows it's a console application which should run in foreground and block until it exits. I'll have a look at it.

FYI: Veyon 4.2 will have basic SASL support for LDAP but only for Linux clients.

**Comment by tobydox** [comment] 2018-12-12 08:09
I'm sorry but I can't reproduce this. I tried the following:

`
veyon-cli networkobjects add room "Test"
for ((i=1; i < 255; ++i)) ; do
  veyon-cli networkobjects add computer "Host $i" host$i.example.com 11:22:33:44:55:66 "Test"
done
`

Afterwards all 254 computers exist.

Since you're not affected by this anyway I'm closing this issue. Thank you for helping us to make Veyon better!

**Closed by tobydox** 2018-12-12 08:09 UTC
