### ISSUE TITLE
Segmentation fault veyon 4.7.3 on Ubuntu 22.04

### ISSUE THREAD

**Issue by brunovila** [veyon/veyon#815] opened 2022-05-31 10:20 UTC
I get a Sementation fault error after installed in Ubuntu 22.04, when I run
`sudo veyon-configurator
`
and when I restart the veyon sercice daemon.

I tried in a fresh install Ubuntu 22.04 and the error is the same.

This is the stacktarce

![image](https://user-images.githubusercontent.com/6134961/171151749-ddc43234-ec74-4d9f-b6be-0c68a0f43000.png)

**Comment by jaumeramos** [comment] 2022-06-01 15:17
Same here.

**Comment by tobydox** [comment] 2022-06-03 13:01
Can you please try the intermediate build at https://github.com/veyon/veyon/releases/download/v4.7.3/veyon_4.7.3.6-ubuntu.jammy_amd64.deb ? It has been built without link-time optimization, just in case there's an LTO-related bug in Ubuntu 22.04.

**Comment by jaumeramos** [comment] 2022-06-03 16:54
Thanks @tobydox the intermediate build 4.7.3.6 you provided works without any segmentation fault.
Will keep testing and will post if there's any problem, but all programs start normally.

**Comment by brunovila** [comment] 2022-06-09 09:55
The intermediate package does not work. This happens on user login

I provide the crash report generated by ubuntu
[crash report](https://drive.google.com/file/d/1khFmZCY-gGyn8vzAQySxQjZdKw28wPDr/view?usp=sharing)

**Comment by Mazhoon** [comment] 2022-07-15 08:16
Commenting out row 89 of configurator/src/MainWindow.cpp, `connect( ui->actionAboutQt, &QAction::triggered, QApplication::instance(), &QApplication::aboutQt );`, seems to fix the crash on Debian Bullseye.

**Comment by tobydox** [comment] 2022-07-27 11:15
Duplicate of #810. Thank's to everyone who helped analysing the issue which now has been fixed via 5097f35a445841f5a9a6ec93c2c08db5a3ce6838.

**Closed by tobydox** 2022-07-27 11:15 UTC
