### ISSUE TITLE
Microsoft Visual C++ Runtime Library - This application has requested to terminate it in an unusual way

### ISSUE THREAD

**Issue by dxdemetriou** [veyon/veyon#396] opened 2018-08-22 11:36 UTC
Only on 32-bit version (64bit version is OK) in Master, there are appearing multiple windows of this message and crashes: Microsoft Visual C++ Runtime Library This application has requested to terminate it in an unusual way .

I had these crashes by selecting multiple rooms and when I used reboot on all computers (I suppose it's because of showing multiple computers once).

**Comment by dxdemetriou** [comment] 2018-09-08 16:30
Yes, It's still happening on Windows 7 32bit.
It seems that Windows 32bit cannot handle multiple computers like Windows 64bit.
I tried to load 1-per-1 computer but it still happens on 80~ computers.

**Comment by dxdemetriou** [comment] 2018-09-09 11:54
I think that this:
https://github.com/veyon/veyon/issues/154
happens after the crash of Veyon Master.
I tried to disable/enable veyon service and reboot but didn't worked,
and I had to uninstall and reinstall Veyon for fixing it.
Can I remove the component which is responsible for locking keyboard/mouse?
For the time I'm using Master on Windows 64bit only.

**Comment by tobydox** [comment] 2018-12-12 13:07
I still can't reproduce the crash so I'm going to close this for now. If you have new information, don't hesitate to respond. The input device issue is fixed in 4.1.5 and newer.

**Closed by tobydox** 2018-12-12 13:07 UTC

**Comment by cjfloss** [comment] 2025-02-14 12:01
I'm still having this issue using Veyon 4.7.5 on Windows 7 32 Bits, when I try to open a website remotely

**Comment by tobydox** [comment] 2025-02-14 12:17
Please note that we do not support Windows 7 any longer as well as old release series.
