### ISSUE TITLE
Veyon service not running when user logout and then login to his session on Linuxmint 18 xfce

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#146] opened 2017-10-10 11:26 UTC
Any news ?

**Comment by jamj2000** [comment] 2017-10-11 20:07
I have not tested it on xfce. However, in linux, veyon-service runs at user level, not system level. This means that you must run veyon-service when logging in and ending at logout. The same for any user.

veyon-service may not have finished at the end of the graphical session and this will prevent it from running again in the next session.

Check if veyon-service is still running when logging off. You can use a tty text terminal for it.

**Comment by orion777** [comment] 2017-10-11 22:59
We use xfce client in our schools. I didn't test with windows client if same problem appears with opened and closed sessions

**Comment by orion777** [comment] 2017-11-08 14:59
Hello
Always the same problem after some users are logging in and loging off. I connected and disconnected 3 users and with the third user the screen is red on the veyon master but on the linuxmint session i typed the command "top" and i can see the veyon-worker running (see the capture) and no veyon-service icon on the taskbar
![capture d ecran_2017](https://user-images.githubusercontent.com/29846901/32551255-2f5c24e4-c490-11e7-97f2-bf18877bfeee.png)
Then i run the veyon-service command in a terminal in this user session and it works, the screen is running on the veyon master.
So what is the problem?

**Comment by orion777** [comment] 2017-11-08 15:03
With another user logging in,  as you can see in this capture, the veyon-service icon isn't running on the taskbar but there is a black frame on the screen monitor in veyon master
![thumbnail_p_20171108_143335](https://user-images.githubusercontent.com/29846901/32555937-5421c0dc-c49e-11e7-96ae-4496ec9c726d.jpg)

**Comment by orion777** [comment] 2017-11-08 15:07
I can confirm that veyon service isn't running when graphical session is logging off

**Comment by orion777** [comment] 2017-11-08 15:49
Of course i added the command to autostart for every user.
Here is the autotstart

![capture d ecran](https://user-images.githubusercontent.com/29846901/32558300-b75645dc-c4a4-11e7-8450-3a0debd87966.png)

**Comment by jamj2000** [comment] 2017-11-08 16:40
Nice desktop  :smirk:

Each OS manage services in a different way.

GNU/Linux recently adopted systemd as service manager. The previous one was system V (upstart in Ubuntu). 

So we need to add some source code for systemd in the project. For now the fast solution is to find out a work-around. I apologize for that.

A solution may be kill veyon-service and veyon-worker at end of graphical logout in order to not interfere in next session. 


I found [this thread in stackoverflow](https://stackoverflow.com/questions/7579438/how-to-execute-a-script-when-xfce-session-ends). It's a bit old, but maybe it are useful.

In file __/usr/bin/xfce4-session__ (I don't know if exists nowadays) add the lines 

```
killall veyon-service
killall veyon-worker
```
Good luck, if you find a solution don't hesitate share it.

**Comment by orion777** [comment] 2018-01-26 13:59
Hello
Always the same problem on linuxmint 18 xfce with latest Veyon 2.0.4 whith multiples logout user.
Any solution?
Thanks you again

**Comment by orion777** [comment] 2018-01-26 14:14
Of course the solution is to create a script running when logout with line killall veyon-service but on xfce i can't find the file where to put this command
Thabks you for help

**Comment by swhaat** [comment] 2018-01-29 09:21
a possibility is to create a systemd service file that gets activated when the user logs in and is deactivated when the user logs out.. 
maybe a good idea for the developers to write a small systemd service which could provide this functionality since most popular distros use systemd..

**Comment by orion777** [comment] 2018-01-29 21:05
Thanks you but i don't know what to do.
There is a dysfunction with veyon service or veyon worker when session is closed up mutiple times by multiple users on xfce. Does someone know how to add a script to kill the process veyon-service when session is closing up on linuxmint 18 xfce 
We actually can't work with veyon on linuxmint 18 because of this problem since several months and we keep italc 3. Thanks you for your help

**Comment by tobydox** [comment] 2018-01-30 09:04
Veyon 4.1.x will come with full systemd support which automatically starts the new separate component "veyon-server" inside graphical user sessions.

**Comment by orion777** [comment] 2018-01-31 19:44
Great but when will you plan to release Veyon 4.1 ?
Regards

**Comment by tobydox** [comment] 2018-02-02 18:24
It'll be available in 2-3 months.

**Comment by orion777** [comment] 2018-04-23 15:17
Hello
Always same problem with the latest Veyon alpha release.
First connexions with login it's ok on the veyon master screen (logged on user _lightdm)
But then after 2 connexions with login, red screen with alert message : service unreachable or not running. But when i check the session with command veyon-ctl service status : it's active (running).
Hope you will find an issue to this big problem with the linux system.

**Comment by tobydox** [comment] 2018-04-23 18:06
Thanks for your feedback! Did you remove all custom autostart entries for veyon-service and veyon-server? Can you set the log level to "Debug", reproduce the issue and look for problems in /tmp/VeyonService.log? Does the server process get started and stopped properly?

**Comment by tobydox** [comment] 2018-06-05 16:32
Closing this until we have more feedback. Veyon 4.1 RC1 will have improved support for session management in the service so it might finally fix the issue. Feel free to reply and/or re-open :-)

**Closed by tobydox** 2018-06-05 16:32 UTC
