### ISSUE TITLE
Veyon makes other applications refresh/flicker

### ISSUE THREAD

**Issue by mgf788** [veyon/veyon#624] opened 2020-03-09 10:50 UTC
Hello All. When I run the Master Version on the computer all works well except most applications refresh all the time e.g. Word, cmd. This makes them pretty unusable. From reading this forum it seems that it may be anything with a network share. In another thread someone suggested stopping the veyon service. I did so and this stopped it. This probably isn't ideal as I think I want the service running on the master computer so that it is accessible from elsewhere. I may be doing something stupid! Thanks.

**Comment by Justsnoopy30** [comment] 2020-04-20 16:55
Confirmed.

**Comment by TPowl** [comment] 2020-10-28 16:11
We also get the apps refresh/flash when the Veyron Master is running. As soon as I close it, app refreshes stop.

**Comment by tobydox** [comment] 2022-07-29 07:27
Unfortunately there's nothing we can do about this since we rely on UltraVNC internally which performs the actual display access. The situation might have improved with recent releases of Veyon which also ship more recent versions of UltraVNC.

**Closed by tobydox** 2022-07-29 07:27 UTC

**Comment by mgf788** [comment] 2022-08-19 13:32
Thanks, much appreciated. Yes, the new versions are much better!

Regards,

Mark.
