### ISSUE TITLE
Problem adding rooms/computers in UserConfig.json on Linuxmint18

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#48] opened 2017-07-07 23:13 UTC
Hello again

I have a problem when adding rooms and computer in Veyon-configurator.
When i save parameters in UserConfig.json after adding room and computers there is nothing then in the following line of the .json file
  },
    "LocalData": {
        "NetworkObjects": {
            "JsonStoreArray": [
            ]
        }
And when i run veyon-master same thing there are no room and computers.

I also have a problem when creating keypaiir in /etc/veyon/keys/private/teacher and /etc/veyon/keys/public/teacher. i'm login as root but it said that i haven't the privileges for these files.
I changed privileges with chmod 777 but same problem again.

Thanks you very much for your help again.

**Comment by tobydox** [comment] 2017-07-10 14:41
Regarding key files one note: please ensure the permissions for all directories in the whole file path are correct. If everyone can read the file but the directory "teacher" is not accessible, things won't work.

The UserConfig.json does not contain rooms or computers but just references (UUIDs) to computers which are checked and shown in the working space. If no computers are shown please ensure the default network object directory is configured (page "General"). You should then see all computers you added via Veyon Configurator in the computer room management view.

**Comment by orion777** [comment] 2017-07-10 23:30
In the page "General" i selected default (store object in local configurationj) and then added room and computer in local data but then when i run italc-master no room and no computer. Is there a local configuration in a globalxmlconfig file? I don't understand why when i add room and computer it isn't definitively saved. Each time when i reload veyon-configurator as root there are no room no computer.

Yes all directories have permissions (read write) for root but when i create keypair here is the result ;  ConfiguratorCore: creating new key pair in "/etc/veyon/keys/private/teacher/key" and "/etc/veyon/keys/public/teacher/key"
2017-07-11T01:09:03.005: [WARN] static bool ConfiguratorCore::createKeyPair(VeyonCore::UserRole, const QString&): key generation failed

Is there a problem with linuxmint disctribution?
Thanks you for your help, i hope to find a solution

**Comment by orion777** [comment] 2017-07-10 23:37
And when i run Veyon-configurator as root i have these messages in the terminal
LocalStore: trying to load unknown JSON value type!
LocalStore: trying to load unknown JSON value type!
LocalStore: trying to load unknown JSON value type!
2017-07-11T01:35:15.775: [ERR] LocalStore: trying to load unknown JSON value type!

**Comment by tobydox** [comment] 2017-07-11 07:58
Oh there seems to be a problem with your Veyon configuration file. Try to remove the file `/etc/xdg/Veyon\ Solutions/Veyon.conf` or run

    veyon-ctl config clear

**Comment by orion777** [comment] 2017-07-11 09:27
I removed the Veyon.conf file and also tried the veyon-ctl config clear command but always same problem.
When i add room and computer in veyon-configurator here is the message in the terminal 
2017-07-11T11:25:13.887: [ERR] LocalStore: trying to save unknown JSON value type!

i send you the veyon.conf file attached
[Veyon.conf.zip](https://github.com/veyon/veyon/files/1138361/Veyon.conf.zip)

**Comment by orion777** [comment] 2017-07-11 09:41
I also have this message when trying to create key pair as root
i did a sudo chmod -R 0755 /etc/veyon/keys/private/teacher like i did with italc 2 but it doesn't work here
![capture d ecran_2017-07-11_11-38-48](https://user-images.githubusercontent.com/29846901/28062252-9cfdcd2a-662d-11e7-9e7f-1e49b491a093.png)

**Comment by tobydox** [comment] 2017-07-11 09:43
Strange, the list is empty. What version of Qt are you using? Are you using special (non-ASCII) characters for rooms or hostnames? Can you try to add a room "test" and a computer "test"? Can you try to set the application language to English temporarily?

**Comment by orion777** [comment] 2017-07-11 09:50
QMake version 2.01a
Using Qt version 4.8.7 in /usr/lib/x86_64-linux-gnu

**Comment by tobydox** [comment] 2017-07-11 09:52
No, that's your Qt4 installation ;-) Use Help -> "About Qt" in Veyon Configurator.

**Comment by orion777** [comment] 2017-07-11 09:52
here are the line message when i run veyon-service in the terminal 

Linuxmint-SalleInfo20 ~ # veyon-service
LocalStore: trying to load unknown JSON value type!
LocalStore: trying to load unknown JSON value type!
2017-07-11T11:51:19.195: [INFO] Exec
11/07/2017 11:51:19 passing arg to libvncserver: -passwd
11/07/2017 11:51:19 passing arg to libvncserver: -rfbport
11/07/2017 11:51:19 passing arg to libvncserver: 11200
11/07/2017 11:51:19 x11vnc version: 3.99.6-16-g85342ca lastmod: 2015-11-14  pid: 2783
11/07/2017 11:51:19 Using X display :0.0
11/07/2017 11:51:19 rootwin: 0xd4 reswin: 0x1a00001 dpy: 0x60006ab0
11/07/2017 11:51:19 
11/07/2017 11:51:19 ------------------ USEFUL INFORMATION ------------------
11/07/2017 11:51:19 
11/07/2017 11:51:19 Wireframing: -wireframe mode is in effect for window moves.
11/07/2017 11:51:19   If this yields undesired behavior (poor response, painting
11/07/2017 11:51:19   errors, etc) it may be disabled:
11/07/2017 11:51:19    - use '-nowf' to disable wireframing completely.
11/07/2017 11:51:19    - use '-nowcr' to disable the Copy Rectangle after the
11/07/2017 11:51:19      moved window is released in the new position.
11/07/2017 11:51:19   Also see the -help entry for tuning parameters.
11/07/2017 11:51:19   You can press 3 Alt_L's (Left "Alt" key) in a row to 
11/07/2017 11:51:19   repaint the screen, also see the -fixscreen option for
11/07/2017 11:51:19   periodic repaints.
11/07/2017 11:51:19 GrabServer control via XTEST.
11/07/2017 11:51:19 
11/07/2017 11:51:19 Scroll Detection: -scrollcopyrect mode is in effect to
11/07/2017 11:51:19   use RECORD extension to try to detect scrolling windows
11/07/2017 11:51:19   (induced by either user keystroke or mouse input).
11/07/2017 11:51:19   If this yields undesired behavior (poor response, painting
11/07/2017 11:51:19   errors, etc) it may be disabled via: '-noscr'
11/07/2017 11:51:19   Also see the -help entry for tuning parameters.
11/07/2017 11:51:19   You can press 3 Alt_L's (Left "Alt" key) in a row to 
11/07/2017 11:51:19   repaint the screen, also see the -fixscreen option for
11/07/2017 11:51:19   periodic repaints.
11/07/2017 11:51:19 X FBPM extension not supported.
11/07/2017 11:51:19 X display is capable of DPMS.
11/07/2017 11:51:19 --------------------------------------------------------
11/07/2017 11:51:19 
LocalStore: trying to load unknown JSON value type!
LocalStore: trying to load unknown JSON value type!
11/07/2017 11:51:19 Default visual ID: 0x20
11/07/2017 11:51:19 Read initial data from X display into framebuffer.
11/07/2017 11:51:19 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5464
11/07/2017 11:51:19 WARNING: Width (1366) is not a multiple of 4. VncViewer has problems with that.
11/07/2017 11:51:19 
11/07/2017 11:51:19 X display :0.0 is 32bpp depth=24 true color
11/07/2017 11:51:19 
11/07/2017 11:51:19 Listening for VNC connections on TCP port 11200
11/07/2017 11:51:19 rfbListenOnTCP6Port error in getaddrinfo: Nom ou service inconnu
11/07/2017 11:51:19 Listening also on IPv6 port 11200 (socket 11)
11/07/2017 11:51:19 Xinerama: Library libXinerama is not available to determine
11/07/2017 11:51:19 Xinerama: the head geometries, consider using -blackout
11/07/2017 11:51:19 Xinerama: if the screen is non-rectangular.
11/07/2017 11:51:19 fb read rate: 2154 MB/sec
11/07/2017 11:51:19 fast read: reset -wait  ms to: 10
11/07/2017 11:51:19 fast read: reset -defer ms to: 10
11/07/2017 11:51:19 The X server says there are 16 mouse buttons.
11/07/2017 11:51:19 screen setup finished.
11/07/2017 11:51:19 

The VNC desktop is:      localhost:5300
11/07/2017 11:51:19 possible aliases:  localhost:11200, localhost::11200
PORT=11200

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval.  It should work with any VNC viewer.  Try it by running:

    x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

**Comment by tobydox** [comment] 2017-07-11 09:53
There's a basic problem with storage of JSON values and we need to figure out where and why.

**Comment by orion777** [comment] 2017-07-11 09:54
This program uses Qt version 5.5.1. (noted in Veyon Configurator - About QT)

**Comment by tobydox** [comment] 2017-07-11 09:55
I should then probably test with Qt 5.5 (which is only supported via compatibility functions in Veyon, Qt >= 5.6 is recommended).

**Comment by tobydox** [comment] 2017-07-11 09:57
Regarding key problems: can you run

    cd /etc/veyon
    find -type d -exec ls -la '{}' ';'

and paste the output here?

**Comment by orion777** [comment] 2017-07-11 10:00
i created a local user which name is prof.
But when i run veyon-configurator with the user prof here is the message
veyon-configurator 
LocalStore: trying to load unknown JSON value type!
LocalStore: trying to load unknown JSON value type!
LocalStore: trying to load unknown JSON value type!
QIODevice::write (QFile, "/tmp/VeyonConfigurator.log"): device not open
2017-07-11T11:56:26.322: [ERR] LocalStore: trying to load unknown JSON value type!
QIODevice::write (QFile, "/tmp/VeyonConfigurator.log"): device not open
2017-07-11T11:56:26.323: [ERR] Configuration not writable : The local configuration backend reported that the configuration is not writable! Please run the Veyon Configurator with higher privileges.

So i run veyon-configurator as root.
But i have noticed that in home/prof there a /.veyon/config/UserConfig.json and /.veyon/Screenshots
Note that the UserConfig.json is empty in this folder
I don't know if the problem can be there

**Comment by orion777** [comment] 2017-07-11 10:02
here is the result : 

find -type d -exec ls -la '{}' ';'
total 20
drwxr-xr-x   3 root root  4096 juil. 11 10:55 .
drwxr-xr-x 172 root root 12288 juil. 11 11:11 ..
drwxr-xr-x   4 root root  4096 juil. 11 10:55 keys
total 16
drwxr-xr-x 4 root root 4096 juil. 11 10:55 .
drwxr-xr-x 3 root root 4096 juil. 11 10:55 ..
drwxr-xr-x 3 root root 4096 juil. 11 10:55 private
drwxr-xr-x 3 root root 4096 juil. 11 10:55 public
total 12
drwxr-xr-x 3 root root 4096 juil. 11 10:55 .
drwxr-xr-x 4 root root 4096 juil. 11 10:55 ..
drwxr-xr-x 2 root root 4096 juil. 11 10:55 teacher
total 8
drwxr-xr-x 2 root root 4096 juil. 11 10:55 .
drwxr-xr-x 3 root root 4096 juil. 11 10:55 ..
total 12
drwxr-xr-x 3 root root 4096 juil. 11 10:55 .
drwxr-xr-x 4 root root 4096 juil. 11 10:55 ..
drwxr-xr-x 2 root root 4096 juil. 11 10:55 teacher
total 8
drwxr-xr-x 2 root root 4096 juil. 11 10:55 .
drwxr-xr-x 3 root root 4096 juil. 11 10:55 ..

**Comment by orion777** [comment] 2017-07-11 11:27
Do you think there is a solution for my problem?
Thanx a lot for your help

**Comment by tobydox** [comment] 2017-07-11 13:50
I don't know. Currently I don't know what to try further. You could try to update to a more recent version of Linux Mint with Qt >= 5.6 and QCA >= 2.1.1.

**Comment by orion777** [comment] 2017-07-11 14:26
OK sad for me .. i'm afraid to keep with old italc version

**Comment by tobydox** [comment] 2017-07-11 15:08
Can you please update your Git repository to the latest version, rebuild and then open the Configurator. Then use File -> Reset configuration and then import the attached file. You should then see a list of two rooms and the first one should contain two computers.
[test.json.zip](https://github.com/veyon/veyon/files/1139333/test.json.zip)

**Comment by orion777** [comment] 2017-07-11 20:12
I noticed that when i change other parameters there no message error and the parameters are saved when i reload the configurator again.
Seems that the problem is only linked with local data. The configurator can't write in the .json file and can't find it. Where is located this file, and is there any problem with privileges concerning this file and the configurator?

**Comment by orion777** [comment] 2017-07-12 16:52
any news with that bug?

**Comment by tobydox** [comment] 2017-07-13 08:57
Good news: I was able to reproduce the issue with Qt 5.5. Do you have a chance to update to Qt >= 5.6? I'll look whether there's a solution for Qt 5.5 later.

**Comment by orion777** [comment] 2017-07-13 09:07
Hello
Thanks you for your message.
Please can you give me the procedure to update QT5.5 to Qt5.6 on Linuxmint 18 ?
Thanx very much for your help

**Comment by orion777** [comment] 2017-07-13 23:02
If it can help you resolving this problem here is a file attached showing message during compilation concerning .json file storage, local data.
![capture d ecran_2017-07-14_01-00-23](https://user-images.githubusercontent.com/29846901/28191349-0ce987f6-6830-11e7-9554-3dbf07c0f2fe.png)

**Comment by tobydox** [comment] 2017-07-15 16:25
Issue is fixed in master branch.

**Closed** 2017-07-15 16:25 UTC
