### ISSUE TITLE
Multi-user mode does not work with Ubuntu 20.04, xrdp and Veyon 4.6

### ISSUE THREAD

**Issue by amato-gianluca** [veyon/veyon#760] opened 2021-10-10 18:02 UTC
Hi,
I am not able to use Veyon (4.6) on Ubuntu 20.04 (installed on both master and clients) in multi-session mode when users connect trough xrdp.  Although a new instance of veyon-server is started for each new user, the master does not show any active session.

If users connect using the console, even concurrently from multiple virtual terminals, everything works as expected. 

I see there is an old issue (https://github.com/veyon/veyon/issues/720) for the same problem as mine, but an older version of Veyon. Could it be the same bug which crept again in the new version ?

**Comment by candiedoperation** [comment] 2021-11-17 13:32
**Difficult to Grab your Computer** when you want to View Screens in your Computer Lab?

Monitoring Center is an **Android / iOS Application for Veyon**. It is a free and open source software for monitoring and controlling computers across multiple platforms. It supports you in teaching in digital learning environments, performing virtual trainings and Monitoring Devices in Computer Laboratories. Learn more About Veyon at https://veyon.io

Get the Source code of Monitoring Center at https://github.com/candiedoperation/Monitoring-Center/
Become my Patron at https://patreon.com/atheesh

Screenshots of the App -
|![Screenshot_1637053110](https://user-images.githubusercontent.com/47198395/141977770-fec81e6e-fc6c-4f07-a491-dcfebd52dc6c.png)|![Screenshot_1637061267](https://user-images.githubusercontent.com/47198395/141977781-df24cb23-3740-4221-924f-66bef4f3c90e.png)|
|---|---|

**Comment by tobydox** [comment] 2022-01-24 09:29
Did you append the session-specific port numbers to the hostname when adding the computers in Veyon Configurator? Alternatively consider trying the Network Discovery add-on which will scan for sessions automatically.

**Comment by amato-gianluca** [comment] 2022-01-26 10:45
I don't think it is a problem with the configuration of the master, but with the way sessions are initialized in the clients. Here follows the results of some experiments I made:

1) When an user logins trough the console, processes veyon-server (owned by root) and veyon-worker (owned by the user) are spawned. The user session appears both in the output of the "who" command and of the "loginctl" command.

2) When an user logins via web trough Guacamole (using the RDP backend), processes veyon-server and veyon-worker are not spawned. The user session appears in the output of "loginctl" but not of "who".

So, my guess is that whatever mechanism is using to intercept logins and launch the server and worker processes, this does not work when users login trough RDP. I am willing to do further experiments, but I would need some hints on the mechanism used to spawn server and worker processes (I would have expected PAM were used, but there is no PAM configuration related to Veyon).

Finally, the problem is still there in Veyon 4.7.1

**Comment by tobydox** [comment] 2022-01-26 12:28
Thank you for the good analysis! I guess the problem is somehow related to how Veyon Service decides for which sessions to start a Veyon Server instance. Can you please paste the output of `loginctl show-session XXX` for an active Guacamole session where no veyon-server instance is launched?

**Comment by tobydox** [comment] 2022-01-26 12:31
In addition, the contents of `/tmp/VeyonService.log` and `/tmp/VeyonServer*.log` would be interesting. First please change the log level to "Debug". Then remove the files, restart the computer and initiate a Guacamole session. Once started, make a copy of the mentioned files and if possible attach them here.

**Comment by amato-gianluca** [comment] 2022-02-01 17:29
Here is the requested data.

[loginctl.log](https://github.com/veyon/veyon/files/7980601/loginctl.log)
[VeyonService.log](https://github.com/veyon/veyon/files/7980602/VeyonService.log)
[VeyonServer.log](https://github.com/veyon/veyon/files/7980607/VeyonServer.log)

I don't know if it's relevant, but there is a single file which matches `/tmp/VeyonServer*.log`.

**Comment by tobydox** [comment] 2022-02-02 07:39
Thank you very much for the log files! From what I can see, the GDM session is staying alive while the remote session is opened (which is fine). However in that case active or multi session mode needs to be enabled. Can you please check whether multi session mode is enabled in the Service configuration tab in the Veyon Configurator? Then log files such as `/tmp/VeyonServer-1.log` etc. should appear for the veyon-server process launched in the 2nd (i.e. the xrdp) session.

**Comment by amato-gianluca** [comment] 2022-02-02 08:16
Sure, mutisession is enabled. This is my configuration file:

[Veyon.conf.txt](https://github.com/veyon/veyon/files/7984630/Veyon.conf.txt)

If you want, I can provide the same logs with multisession disabled.

**Comment by tobydox** [comment] 2022-02-02 08:30
Thank you. After a closer look, Veyon Service indeed tries to start a Veyon Server instance for session "1" (VeyonService.log line 52) but it looks like the Server doesn't start properly inside these sessions, likely due to an x11vnc problem. In that case can you please enable the "Write to logging system of operating system" option (page "General settings" after switching to View -> Advanced) and try again. Afterwards, `journalctl -u veyon-service` should contain the whole output of all Veyon Server instances, including the output (and hopefully error messages) printed by the internal builtin x11vnc server.

**Comment by tobydox** [comment] 2022-02-02 08:31
Additionally you could try to add `-noshm` to the *Custom x11vnc parameters* field in the VNC server options which could resolve x11vnc startup problems.

**Comment by tobydox** [comment] 2022-02-16 12:54
Any news?

**Comment by amato-gianluca** [comment] 2022-02-16 21:18
Sorry for being late. I  have enabled the "Write to logging system of operating system" option and added the "-noshm" custom parameter to x11vnc. The relevant sections of the ``Veyon.conf`` file contain:
```
[Logging]
LogLevel=5
LogToSystem=true

[X11Vnc]
ExtraArguments=-noshm
```

I extract two logs, the first one relative to a login trough the console, the other for a login trough guacamole/xrdp. In the first log there are many messages related to X11Vnc. In the second log file these messages do not appear, but there is an error related to missing Qt plugins. Here follow the two logs:

[login-console.txt](https://github.com/veyon/veyon/files/8083608/login-console.txt)
[login-guacamole.txt](https://github.com/veyon/veyon/files/8083609/login-guacamole.txt)

**Comment by tobydox** [comment] 2022-02-17 13:07
It looks like the Veyon Server instance can't access the X11 session (at display :10.0), I guess due to insufficient privileges to read ~/.Xauthority. Where are your home directories and ~/.Xauthority located? On a network share? If so, which filesystem?

**Comment by amato-gianluca** [comment] 2022-02-20 23:04
> It looks like the Veyon Server instance can't access the X11 session (at display :10.0), I guess due to insufficient privileges to read ~/.Xauthority. Where are your home directories and ~/.Xauthority located? On a network share? If so, which filesystem?

Oh, yes!! You are right.

Home directories are mounted in NFSv4, using krb5 security types. I had to change to sec=sys security type and add the no_root_squash option, and now veyon-server correctly starts even when the session is launched via Guacamole or directly 
trough xrdp. Do you have any idea while it works without these options when the login is trough the console ?

Unfortunately, I still have some problems, but they seems of a completely different kind, so I will probably submit a different bug report after I collect other evidence.

Tobias, thanks a  lot for your help!!

**Comment by tobydox** [comment] 2022-02-22 12:18
Home directories on network shares are difficult case which Veyon Service currently doesn't handle very well. In general the Veyon Service launches the Veyon Server instances as direct child processes (while using the environment variables from the user session processes) so they run as `root` and not as the logged in user (which is intended to prevent users from killing veyon-server processes). The drawback of this approach is, that Veyon Server runs without user-session specific filesystem credentials (AFAIK this involves user, session or process keyrings attached to the user processes).

For a generic solution, someone with deeper knowledge of NFS, kernel keys/credentials management etc. would have to extend `LinuxServiceCore::startServer()` (https://github.com/veyon/veyon/blob/master/plugins/platform/linux/LinuxServiceCore.cpp#L143) and/or the `LinuxServerProcess` class such that it obtains the credentials/keyrings from the user processes and stores it in the newly created process.

**Comment by tobydox** [comment] 2022-07-29 07:24
Closing due to lack of viable solutions regarding starting Veyon Server instances with NFS-mounted homes. A possible work around would be to disable the Veyon Service and start veyon-server manually through autostart entries. The only drawback is that users would be able to kill the veyon-server processes.

**Closed by tobydox** 2022-07-29 07:24 UTC
