### ISSUE TITLE
See how long a user has been logged in

### ISSUE THREAD

**Issue by paul-pascual** [veyon/veyon#876] opened 2023-03-29 20:20 UTC
Hi,
I have a suggestion for veyon.
I need to be able to rotate the students in my computer room every 30 minutes. But for now, I use a spreadsheet with the arrival time and a formula calculating the exit time.
I would like to have this directly in veyon next to the user name for example.

Thanks in advance :)

**Comment by tobydox** [comment] 2023-03-31 11:05
Thanks for the suggestion. This is a duplicate of #821 and is going to be implemented in the upcoming 4.8.0 release.

**Closed by tobydox** 2023-03-31 11:05 UTC

**Comment by paul-pascual** [comment] 2023-03-31 19:20
Thank you !
I'm sorry for the duplicate :/

**Comment by tobydox** [comment] 2023-04-03 18:10
Don't worry, it's just for documentation purposes so we keep track of duplicates ;-)

**Comment by paul-pascual** [comment] 2023-04-09 10:18
Other question, when version 4.8 is released ?

**Comment by tobydox** [comment] 2023-04-11 07:02
This month ;-)

**Comment by paul-pascual** [comment] 2023-04-14 10:23
Thank you :)

**Comment by paul-pascual** [comment] 2023-04-30 10:47
Hi,
Hi have updated all my pcs but but i don’t see how to display the connection time :/
