### ISSUE TITLE
Veyon blocking software popups, Photoshop CS5

### ISSUE THREAD

**Issue by wakka9876** [veyon/veyon#295] opened 2018-03-22 12:52 UTC
Not sure if you've come across this at all
If a student is using Photoshop while Veyon is running in demo mode, it stops all software popups appearing on screen, for example the right click to change brush size doesnt pop up, but starts working again as soon as Veyon is closed on the teachers PC (and stops when Veyon is relaunched etc etc) 

I'm hoping this is something as simple as a config issue but if you have any suggestions that would be great

Thanks

**Comment by orion777** [comment] 2018-03-22 23:09
I noticed the same problem with graphic programs like Solidworks and Sweethome 3d. Maybe there is a problem with veyon config when running 3d / openGL programs. When Veyon master is closed these programs works. It is a problem in our classroom because students works with these programs. 
Any idea to fix this issue?
Thanks a lot

**Comment by tobydox** [comment] 2018-03-23 09:29
Can you try to alter some of the VNC server configuration options such as capturing of layered windows or full screen polling?

**Comment by orion777** [comment] 2018-03-23 13:49
Where are the options of the VNC server. I can't find.
Thanks you very much

**Comment by wakka9876** [comment] 2018-03-23 18:48
I have a technician looking at it after the weekend, I'll reply as soon as they get back to me

**Comment by orion777** [comment] 2018-03-29 11:21
Hello
Any news concerning this problem? It is really a problem here for using Veyon.
Thanks you for your help

**Comment by orion777** [comment] 2018-04-06 08:37
Will you fix this issue in the next updated release?
Regards

**Comment by tobydox** [comment] 2018-04-11 07:53
Can you try with Veyon 4.1 Alpha? It contains an updated VNC server.

**Comment by orion777** [comment] 2018-04-27 12:39
Very strange. .I did a new installation of Veyon 4.0.7 on new machines (veyon master + clients)  and it works. No problem with pop ups and graphical softwares.

But concerning the first computers where i installed veyon 4.0.1 when it was released, the problem is always here even if i try with newest versions (veyon 4.07 or Veyon 4.1 alpha)
I desinstalled veyon 4.0.1, removed all configuration files. i don't know what to do except reinstalling OS system on these computers.

**Comment by tobydox** [comment] 2018-05-02 16:39
It's probably a very specific issue e.g. with your graphics driver or installed DLLs, runtimes etc. I'm sorry that I can't provide you with a solution and therefore I'll close the issue for now. Feel free to post any additional information or news - maybe we find the issue and can solve it.

**Closed by tobydox** 2018-05-02 16:39 UTC
