### ISSUE TITLE
[ERR] [UltraVNC]

### ISSUE THREAD

**Issue by chrisgerman** [veyon/veyon#548] opened 2019-08-16 16:48 UTC
I'm getting the following errors in VeyonServer.log after a newly installed Veyon 4.2.4 with Windows 10 Enterprise LTSC 1809 Build 17763.678. Also Master doesn't see the computer or so... I'm at lost. 

`
2019-08-15T17:08:44.950: [INFO] [UltraVNC] int WinVNCAppMain() : server created ok
2019-08-15T17:08:44.951: [ERR] [UltraVNC] int WinVNCAppMain() : ***************** SDEvent created 
 --The system cannot find the file specified.
2019-08-15T17:08:44.951: [ERR] [UltraVNC] DWORD imp_desktop_thread(LPVOID) : OpenInputdesktop OK
 --The parameter is incorrect.
2019-08-15T17:08:44.951: [INFO] [UltraVNC] DWORD imp_desktop_thread(LPVOID) : SelectHDESK to Default (478) from d0
2019-08-15T17:08:44.952: [INFO] [UltraVNC] virtual void* vncSockConnectThread::run_undetached(void*) : started socket connection thread
2019-08-15T17:30:47.415: [INFO] [UltraVNC] int WinVNCAppMain() : ################## Closing Imp Thread
2019-08-15T17:30:47.415: [ERR] [UltraVNC] int WinVNCAppMain() : ################## SHUTING DOWN SERVER ####################
 --Attempt to release mutex not owned by caller.
2019-08-15T17:30:47.415: [INFO] [UltraVNC] vncServer::~vncServer() : shutting down server object1
2019-08-15T17:30:47.415: [INFO] [UltraVNC] virtual void* vncSockConnectThread::run_undetached(void*) : accepted connection from 4.0.0.0
2019-08-15T17:30:47.415: [ERR] [UltraVNC] virtual void* vncSockConnectThread::run_undetached(void*) : quitting socket connection thread
 --An operation was attempted on something that is not a socket.
2019-08-15T17:30:48.447: [ERR] [UltraVNC] VBool VSocket::Close() : closing socket
 --No connection could be made because the target machine actively refused it.
2019-08-15T17:30:48.447: [ERR] [UltraVNC] VBool VSocket::Close() : closing socket
 --An operation was attempted on something that is not a socket.
`

**Comment by tobydox** [comment] 2021-09-10 13:51
Sorry for the late feedback. I believe the issue is fixed in recent versions of Veyon.

**Closed by tobydox** 2021-09-10 13:51 UTC
