### ISSUE TITLE
LDAP Settings

### ISSUE THREAD

**Issue by Avaryan** [veyon/veyon#37] opened 2017-06-27 11:53 UTC
Having issues correctly binding to LDAP. 

LDAP server and port are correct. This test is successful.
Fixed base DN is unsuccessful, but when I toggle the option to 'Discover bad DN by naming context' and leave the box blank that test is successful and returns a base DN identical to what I typed in the first time.

I can't get anything under the 'Environment settings' to work correctly, but I'll worry about that after fixing the Base DN issue.

Part of the DN would be dc=local, not sure if that's a problem.

**Comment by tobydox** [comment] 2017-06-28 07:03
Does the bind itself work? What is your complete base DN?

**Comment by RvdH72** [comment] 2017-06-28 13:36
With Veyon 4 RC1 (version 3.99.5) I managed to setup LDAP with only one attribute not working ('Computer MAC address attribute'), so I cannot do a Wake-On-Lan with Veyon. A already asked Toby by gmail for a solution, because I could find it in the documentation. All try Veyon 4 RC2 (3.99.6) first, maybe it is solved in that version.

According to your post, LDAP binding is working, but you are stuck at Base DN.
I opened 'Active Directory Users and Computers' , went to the domain and looked under the 'Properties' for the Value in 'distinguishedName' in the Attribute Editor. Copy/paste that to the Veyon Configurator.

So Fixed base DN should be: DC=<domain>,DC=local

**Comment by tobydox** [comment] 2017-07-06 09:01
Any progress on this?

**Comment by tobydox** [comment] 2017-07-11 09:12
Closing this due to missing response. Feel free to request for re-open.

**Closed by tobydox** 2017-07-11 09:12 UTC

**Comment by Avaryan** [comment] 2017-07-26 19:13
Sorry for the delay in response, I had other tasks to complete. I'll be coming back to this shortly.

In the mean time, please reopen this.

**Comment by Avaryan** [comment] 2017-07-26 19:25
![image](https://user-images.githubusercontent.com/1270366/28639556-a402d90e-7216-11e7-8379-0ce64d26a2ba.png)

**Comment by Avaryan** [comment] 2017-07-26 19:27
![image](https://user-images.githubusercontent.com/1270366/28639612-d4d4a972-7216-11e7-8979-19fe2886eec9.png)

Fresh install. No others settings have been changed yet.

**Comment by Avaryan** [comment] 2017-07-26 19:28
@tobydox Please re-open.

**Comment by tobydox** [comment] 2017-07-27 05:25
iTALC didn't have LDAP support so this is not a regression ;-) Anyways I'm glad you fixed it. Entering bind credentials would have been my next suggestion.

**Comment by Avaryan** [comment] 2017-07-27 11:33
iTalc (version 2) had something in it that let me specify a domain group so that only people in that group could use the master client. 

@tobydox How would I do that with Veyon?

**Comment by tobydox** [comment] 2017-08-06 18:21
With Veyon you currently will have to set up LDAP/AD integration and then use the LDAP groups in access control (switch backend to LDAP and re-open Veyon Configurator).
