### ISSUE TITLE
Remote control does not transmit Cyrillic

### ISSUE THREAD

**Issue by mrkaban** [veyon/veyon#625] opened 2020-03-17 13:18 UTC
Hello, I wrote earlier, and they said that in the next versions it will be fixed, but it still does not work, maybe something needs to be done additionally?

The problem is as follows: With remote control, only English characters are transmitted, Russians are not transmitted. Many teachers write to me about this problem. What can they say?

**Comment by s-r-grass** [comment] 2020-11-17 13:57
Joining the problem, no solution found yet?

**Comment by maximusend** [comment] 2021-05-21 10:51
Version 4.5.5. Problem still exists.

**Comment by mrkaban** [comment] 2021-05-21 10:55
I confirm!

**Comment by tobydox** [comment] 2021-06-04 12:09
This is a general difficulty with VNC, see for example https://forum.ultravnc.net/viewtopic.php?f=47&t=18801#p72344 (last post) for details. Unfortunately I don't know how we could fix this to work as expected out-of-the-box.

**Comment by tobydox** [comment] 2021-11-02 14:53
This is a duplicate of #590 and we don't have a solution at the moment, we're sorry.

**Closed by tobydox** 2021-11-02 14:53 UTC
