### ISSUE TITLE
Configuration and connecting

### ISSUE THREAD

**Issue by AlessandroPhilips** [veyon/veyon#112] opened 2017-09-16 13:08 UTC
dear
I can not connect to my computer because something of this computer has not been verified with the client please help me

**Comment by orion777** [comment] 2017-09-16 19:18
Hello
What is exactly your problem?
Do you use key authentification or ldap authentification?

**Comment by joswolf** [comment] 2017-09-17 06:25
Hello, I have a similar problem, a problem with **validating a remote computer**. I'm about verifying with logins and passwords, key validation works ok. When checking the master and client authentication, everything is ok, and when the client tries to connect, the client reports a **verification error** and does not join. I'm sending both client and master screenshots. I do not know where there might be a mistake. Thanks for any help.
![test_klientpc](https://user-images.githubusercontent.com/32029341/30518557-97d8a962-9b81-11e7-83c2-b42639e7c8bc.jpg)
![test_masterpc](https://user-images.githubusercontent.com/32029341/30518558-97db44f6-9b81-11e7-8859-5d4aeb4823cf.jpg)

**Comment by orion777** [comment] 2017-09-17 10:07
Did you copy the public key in the righ folder?

**Comment by joswolf** [comment] 2017-09-17 15:30
Hello, I have no problem with verification key, it works ok. The problem is logon authentication.

**Comment by AlessandroPhilips** [comment] 2017-09-19 16:04
i have the same problem as jofwolf

**Comment by AlessandroPhilips** [comment] 2017-09-19 16:26
orion i use the configuration ldab

**Comment by bf28** [comment] 2017-09-25 17:16
Hello, I also have the same issue as joswolf. Is there a fix for this issue?
Thanks

**Comment by bf28** [comment] 2017-09-27 15:45
Hello, I was able to configure veyon on all the computers at my school, but now I have a different issue. Suddenly the program crashes. See attached screenshot. I'm using Win 10

Thanks
![capture](https://user-images.githubusercontent.com/32274269/30923245-4c564d28-a379-11e7-9550-92e84dce510b.PNG)

**Comment by AlessandroPhilips** [comment] 2017-09-28 21:46
bf28 what does the client computer says when you try to connect is it the same problem or not as joswolf and me

**Comment by bf28** [comment] 2017-09-29 12:42
alessandrophillips, my issue was that I forgot to copy the keys in both the host and client, but I took care of it.

**Comment by asif138** [comment] 2017-11-09 09:59
how to add client computer in master?

**Comment by Ben-Ronlund** [comment] 2017-12-12 05:41
Is there a reason why the client PCs are required to have both the private and public keys?
When connecting from a Windows 10 x64 master to a Windows 10 x64 client, if the client does not have the private key the connection does not work.

**Comment by Faheemkalwar** [comment] 2018-01-16 12:23
Dear Orion777 can i install Veyon software in my computer lab in two windows one for veyon Master and other for client i have no server ..and how to configuration?

**Comment by tobydox** [comment] 2018-06-05 16:30
Thank you all for your feedback! The issue should be fixed in recent releases of Veyon - feel free to reply and/or re-open if you still can reproduce this with current versions.

**Closed by tobydox** 2018-06-05 16:30 UTC
